/* Ruta de la ilustración de portada (la sustituye el script de build). */
const HERO_IMG = '__HERO_IMG__';

/* =========================================================================
   CONTENIDO DEL PORTAL
   Todo el contenido vive aquí como datos. Cada entrada tiene un id estable,
   un tipo y texto indexable: es el mismo formato que usará el buscador y,
   más adelante, la ingesta para embeddings/RAG (ver ARCH en app.js).
   ========================================================================= */

const LABS = [
  { id:'gd', file:'labs/descenso-gradiente.html', url:'https://claude.ai/artifact/7rehM197pCLcHNGFYSan48',
    t:'Descenso de gradiente', d:'SGD, Momentum, RMSProp y Adam compiten sobre cuatro superficies de pérdida. Cambia la tasa de aprendizaje, el punto inicial y el ruido.',
    area:'math', tags:['optimización','gradiente','adam','sgd','learning rate'] },
  { id:'overfit', file:'labs/sobreajuste.html', url:'https://claude.ai/artifact/Hkie25qLqTk28v12ghH8ke',
    t:'Sobreajuste y regresión polinómica', d:'Sube el grado del polinomio y observa cómo el error de validación forma una U. Regularización L2 incluida.',
    area:'ml', tags:['regresión','sesgo','varianza','validación'] },
  { id:'reg', file:'labs/regularizacion.html', url:'https://claude.ai/artifact/U6v71swdSQLwPyzHyDxPuJ',
    t:'Lasso contra Ridge', d:'La geometría del rombo L1 y el círculo L2, y los caminos de regularización de un modelo de 8 variables.',
    area:'ml', tags:['regularización','l1','l2','lasso','ridge'] },
  { id:'tree', file:'labs/arbol-decision.html', url:'https://claude.ai/artifact/86UQXvnXQjZA8vAFoLkFXF',
    t:'Árbol de decisión y Random Forest', d:'El árbol crece corte a corte buscando la menor impureza de Gini. Compáralo con un bosque de 25 árboles.',
    area:'ml', tags:['árbol','gini','random forest','ensemble','clasificación'] },
  { id:'kmeans', file:'labs/kmeans.html', url:'https://claude.ai/artifact/FbqXKEiCZazzWpjzEu1vHS',
    t:'K-means paso a paso', d:'Asignar y actualizar hasta converger. Inicialización aleatoria contra k-means++ y método del codo.',
    area:'ml', tags:['clustering','no supervisado','centroides'] },
  { id:'sigmoid', file:'labs/sigmoide.html', url:'https://claude.ai/artifact/7X1Y94b5XUoyW7bHAWTLwh',
    t:'La función sigmoide', d:'La activación, su derivada y la saturación. Comparación con tanh y ReLU.',
    area:'dl', tags:['activación','neurona','derivada'] },
  { id:'boundary', file:'labs/frontera-decision.html', url:'https://claude.ai/artifact/F4M3A9oSiL7hkDrStpSUT4',
    t:'Frontera de decisión de una red', d:'Entrena un MLP en directo sobre círculos, XOR o espirales y mira qué aprende cada neurona.',
    area:'dl', tags:['mlp','red neuronal','clasificación','relu'] },
  { id:'backprop', file:'labs/red-neuronal.html', url:'https://claude.ai/artifact/TDbpGxeh9QSHQpTmuo1wBY',
    t:'Backpropagation paso a paso', d:'Una red 3→4→3 con softmax y entropía cruzada: los 11 pasos de una iteración con números reales.',
    area:'dl', tags:['backprop','softmax','entropía cruzada','gradiente'] },
  { id:'attn', file:'labs/atencion.html', url:'https://claude.ai/artifact/VbXKZaAct7gVB3KafTEaob',
    t:'Visualizador de atención', d:'Query, Key y Value con las cuentas a la vista, dos cabezas y máscara causal.',
    area:'llm', tags:['attention','transformer','qkv','self-attention'] },
];

/* Áreas temáticas. Cada tema: t título, d definición breve, lab (id de laboratorio), art (id de artículo). */
const AREAS = [
  { id:'ml', t:'Machine Learning', kicker:'Algoritmos clásicos', d:'Modelos que aprenden patrones a partir de datos tabulares o vectores de características: la base de todo lo demás.', topics:[
    {t:'Introducción al ML', d:'Aprender una función a partir de ejemplos en vez de programarla a mano: datos, modelo, pérdida y optimizador.', lab:'overfit'},
    {t:'Aprendizaje supervisado', d:'Se entrena con pares entrada–respuesta correcta para predecir la respuesta en casos nuevos.'},
    {t:'Aprendizaje no supervisado', d:'Solo hay datos, sin etiquetas: se busca estructura, grupos o representaciones compactas.', lab:'kmeans'},
    {t:'Aprendizaje por refuerzo', d:'Un agente actúa en un entorno y aprende qué acciones maximizan la recompensa acumulada.'},
    {t:'Regresión', d:'Predecir un valor numérico continuo, como un precio o una temperatura.', lab:'overfit', art:'linear-regression'},
    {t:'Clasificación', d:'Predecir una categoría. La salida suele ser una probabilidad por clase.', lab:'boundary', art:'logistic-regression'},
    {t:'Clustering', d:'Agrupar puntos parecidos sin conocer los grupos de antemano: K-means, DBSCAN, jerárquico.', lab:'kmeans'},
    {t:'Reducción de dimensionalidad', d:'Comprimir muchas variables en pocas conservando la información: PCA, t-SNE, UMAP.'},
    {t:'Ensemble Learning', d:'Combinar muchos modelos débiles para obtener uno fuerte: bagging, boosting y stacking.', lab:'tree'},
    {t:'Random Forest', d:'Muchos árboles entrenados sobre muestras bootstrap y subconjuntos de variables que votan la predicción.', lab:'tree', art:'random-forest'},
    {t:'Gradient Boosting', d:'Árboles en serie donde cada uno corrige el error residual de los anteriores siguiendo el gradiente de la pérdida.', art:'gradient-boosting'},
    {t:'XGBoost', d:'Implementación de gradient boosting con regularización y optimizaciones de sistema; referente en datos tabulares.', art:'gradient-boosting'},
    {t:'SVM', d:'Busca el hiperplano de máximo margen entre clases; con kernels separa datos no lineales.'},
    {t:'KNN', d:'Predice según los k vecinos más cercanos. No entrena nada: guarda los datos y compara distancias.'},
    {t:'Naive Bayes', d:'Aplica el teorema de Bayes suponiendo variables independientes dada la clase. Rápido y sólido en texto.'},
    {t:'Regularización L1 y L2', d:'Penalizar los pesos grandes para generalizar mejor; L1 además selecciona variables.', lab:'reg'},
  ]},
  { id:'dl', t:'Deep Learning', kicker:'Redes neuronales', d:'Modelos formados por capas de neuronas que aprenden representaciones jerárquicas: visión, audio, texto.', topics:[
    {t:'Redes neuronales', d:'Composición de capas lineales y activaciones no lineales entrenada con descenso de gradiente.', lab:'boundary', art:'neural-networks'},
    {t:'Perceptrón', d:'La neurona original de Rosenblatt: suma ponderada y umbral. Solo separa clases linealmente separables.', lab:'sigmoid'},
    {t:'MLP', d:'Perceptrón multicapa: capas ocultas totalmente conectadas capaces de aproximar funciones no lineales.', lab:'boundary', art:'neural-networks'},
    {t:'Backpropagation', d:'La regla de la cadena aplicada de la salida hacia la entrada para obtener el gradiente de cada peso.', lab:'backprop', art:'neural-networks'},
    {t:'Descenso de gradiente', d:'Actualizar los pesos un paso en contra del gradiente de la pérdida; variantes SGD, Momentum, Adam.', lab:'gd'},
    {t:'CNN', d:'Redes convolucionales: filtros compartidos que recorren la imagen y detectan bordes, texturas y objetos.'},
    {t:'RNN', d:'Redes recurrentes que procesan secuencias manteniendo un estado oculto paso a paso.'},
    {t:'LSTM', d:'RNN con puertas que controlan qué recordar y qué olvidar, para dependencias largas.'},
    {t:'Attention', d:'Cada elemento de una secuencia combina información de los demás ponderada por relevancia.', lab:'attn'},
    {t:'Transformers', d:'Arquitectura basada solo en atención y capas feed-forward; base de los LLM actuales.', route:'transformer', art:'transformers'},
    {t:'Embeddings', d:'Vectores densos que representan palabras, imágenes o usuarios de forma que la cercanía refleja similitud.'},
    {t:'Fine-tuning', d:'Continuar el entrenamiento de un modelo preentrenado con datos de una tarea concreta.'},
    {t:'LoRA / QLoRA', d:'Fine-tuning eficiente: se congelan los pesos y se entrenan matrices de bajo rango; QLoRA además cuantiza a 4 bits.'},
  ]},
  { id:'math', t:'Matemáticas para IA', kicker:'Fundamentos', d:'Lo mínimo imprescindible para leer un paper y entender qué hace un modelo por dentro.', topics:[
    {t:'Álgebra lineal', d:'Vectores, matrices y productos: todo modelo es, al final, multiplicación de matrices.'},
    {t:'Cálculo', d:'Cómo cambian las funciones: la base para optimizar la pérdida.'},
    {t:'Derivadas', d:'Pendiente de una función en un punto; la regla de la cadena permite derivar composiciones.', lab:'sigmoid'},
    {t:'Gradientes', d:'Vector de derivadas parciales: indica la dirección de máxima subida de la pérdida.', lab:'gd'},
    {t:'Probabilidad', d:'Lenguaje para la incertidumbre: distribuciones, esperanza, probabilidad condicionada.'},
    {t:'Estadística', d:'Inferir propiedades de una población a partir de muestras; estimación, contrastes, intervalos.'},
    {t:'Teorema central del límite', d:'La media de muchas variables independientes tiende a una normal, sea cual sea su distribución original.'},
    {t:'Bayes', d:'P(A|B) = P(B|A)·P(A)/P(B): actualizar creencias con evidencia nueva.'},
    {t:'Optimización', d:'Encontrar los parámetros que minimizan una función: convexidad, mínimos locales, puntos de silla.', lab:'gd'},
    {t:'Métodos numéricos', d:'Cálculo aproximado con ordenadores: estabilidad, precisión en coma flotante, softmax estable.'},
  ]},
  { id:'prog', t:'Programación', kicker:'Herramientas', d:'El ecosistema de Python con el que se construye casi todo el machine learning actual.', topics:[
    {t:'Python', d:'El lenguaje de facto para datos e IA por su legibilidad y su ecosistema.'},
    {t:'NumPy', d:'Arrays n-dimensionales y álgebra lineal vectorizada; la base de todas las demás librerías.'},
    {t:'Pandas', d:'DataFrames para cargar, limpiar, unir y agregar datos tabulares.'},
    {t:'Matplotlib', d:'La librería de gráficos de referencia para explorar datos y resultados.'},
    {t:'Scikit-learn', d:'API uniforme fit/predict para ML clásico, preprocesado, validación y métricas.', art:'logistic-regression'},
    {t:'PyTorch', d:'Tensores con autograd y GPU; el framework dominante en investigación y LLM.', route:'transformer', art:'neural-networks'},
    {t:'TensorFlow', d:'Framework de Google con Keras como API de alto nivel y buen soporte de despliegue.'},
    {t:'Hugging Face', d:'Hub de modelos y datasets y las librerías transformers, datasets y peft.'},
  ]},
  { id:'llm', t:'LLM', kicker:'Modelos de lenguaje', d:'Cómo funcionan los modelos de lenguaje grandes, de la tokenización a los agentes.', topics:[
    {t:'Arquitectura Transformer', d:'Bloques de atención multi-cabeza y feed-forward con conexiones residuales y normalización.', route:'transformer', art:'transformers'},
    {t:'Tokenización', d:'Partir el texto en unidades (a menudo subpalabras BPE) y asignar a cada una un id.', route:'transformer'},
    {t:'Embeddings', d:'Cada token id se convierte en un vector aprendido de dimensión d_model.', route:'transformer'},
    {t:'Self-Attention', d:'Cada token calcula cuánto atender a los demás de la misma secuencia.', lab:'attn', art:'transformers'},
    {t:'Q, K y V', d:'Proyecciones de cada token: qué busca (Query), qué ofrece (Key) y qué transmite (Value).', lab:'attn'},
    {t:'Multi-Head Attention', d:'Varias atenciones en paralelo, cada una en su subespacio, concatenadas al final.', route:'transformer'},
    {t:'Positional Encoding', d:'Información de posición sumada a los embeddings, porque la atención por sí sola no conoce el orden.', route:'transformer'},
    {t:'Pretraining', d:'Entrenar con enormes cantidades de texto a predecir el siguiente token.'},
    {t:'Fine-tuning', d:'Adaptar el modelo preentrenado a instrucciones o dominios con datos supervisados o preferencias.'},
    {t:'RAG', d:'Recuperar documentos relevantes con búsqueda vectorial e incluirlos en el prompt para responder con datos propios.'},
    {t:'Agentes IA', d:'LLM que planifican y usan herramientas (APIs, código, búsqueda) en un bucle para completar tareas.'},
    {t:'Modelos locales', d:'Ejecutar LLM abiertos en tu propio hardware, normalmente cuantizados (GGUF, llama.cpp, Ollama).'},
    {t:'Inferencia', d:'Generar tokens uno a uno: KV cache, batching, cuantización y estrategias de muestreo.', route:'transformer'},
  ]},
  { id:'mlops', t:'MLOps', kicker:'Producción', d:'Llevar modelos a producción de forma reproducible, observable y segura.', topics:[
    {t:'Docker', d:'Contenedores que empaquetan código, dependencias y modelo para que funcione igual en cualquier sitio.'},
    {t:'APIs', d:'Exponer el modelo como servicio HTTP con contratos claros de entrada y salida.'},
    {t:'FastAPI', d:'Framework Python para APIs con validación por tipos (Pydantic) y documentación automática.'},
    {t:'Bases de datos', d:'Guardar datos de entrenamiento, predicciones y metadatos de forma consultable.'},
    {t:'PostgreSQL', d:'Base de datos relacional robusta; con pgvector también sirve como base vectorial.'},
    {t:'Vector databases', d:'Índices de búsqueda por similitud sobre embeddings: pgvector, Qdrant, FAISS.'},
    {t:'Git', d:'Control de versiones del código; con DVC o LFS también de datos y modelos.'},
    {t:'CI/CD', d:'Tests y despliegues automáticos en cada cambio: GitHub Actions, GitLab CI.'},
    {t:'Despliegue de modelos', d:'Batch, tiempo real o en el borde; versionado de modelos y despliegues graduales.'},
    {t:'Monitorización', d:'Vigilar latencia, errores y deriva de datos para saber cuándo reentrenar.'},
    {t:'GPUs', d:'Hardware paralelo para multiplicaciones de matrices; la memoria VRAM limita el tamaño del modelo.'},
    {t:'Cloud computing', d:'Infraestructura bajo demanda para entrenar y servir: AWS, GCP, Azure.'},
  ]},
  { id:'research', t:'Investigación', kicker:'Estado del arte', d:'De los papers fundacionales a las líneas abiertas de la IA actual.', topics:[
    {t:'Papers fundamentales', d:'Los trabajos que definieron el campo: backprop, CNN, LSTM, Transformer, BERT, GPT.', route:'papers'},
    {t:'Papers recientes', d:'LoRA, RAG, CLIP y otros trabajos que marcan cómo se construyen los sistemas actuales.', route:'papers'},
    {t:'Estado del arte', d:'Qué funciona hoy en cada tarea y con qué coste: benchmarks y sus limitaciones.'},
    {t:'Arquitecturas emergentes', d:'Mixture of Experts, modelos de espacio de estados y otras alternativas o complementos al Transformer.'},
    {t:'IA multimodal', d:'Modelos que combinan texto, imagen, audio y vídeo en un mismo espacio de representación.'},
    {t:'Modelos fundacionales', d:'Modelos grandes preentrenados de propósito general que se adaptan a muchas tareas.'},
    {t:'Robótica', d:'Aprendizaje de políticas de control, simulación y transferencia al mundo real.'},
    {t:'IA científica', d:'ML aplicado a ciencia: plegamiento de proteínas, materiales, clima, matemáticas.'},
  ]},
];

/* Biblioteca de papers. Solo referencias reales y verificables. */
const PAPERS = [
  { id:'backprop-1986', arts:['neural-networks'], t:'Learning representations by back-propagating errors', a:'D. E. Rumelhart, G. E. Hinton, R. J. Williams', y:1986, v:'Nature 323, 533–536', area:'Redes neuronales',
    p:'Cómo entrenar redes con capas ocultas, cuyos pesos no tienen un valor objetivo directo.',
    c:'Popularizó la retropropagación del error: la regla de la cadena para calcular el gradiente de todos los pesos.',
    arch:'Redes multicapa con activaciones sigmoides.', r:'Es el algoritmo con el que se entrenan prácticamente todas las redes neuronales actuales.', impl:'loss.backward() en PyTorch', lab:'backprop' },
  { id:'lstm-1997', t:'Long Short-Term Memory', a:'S. Hochreiter, J. Schmidhuber', y:1997, v:'Neural Computation 9(8), 1735–1780', area:'RNN',
    p:'Las RNN no aprendían dependencias largas porque el gradiente se desvanecía o explotaba.',
    c:'Una celda con memoria y puertas multiplicativas que mantienen el flujo de error constante.',
    arch:'Celda LSTM (en la versión original, puertas de entrada y salida; la puerta de olvido se añadió después).', r:'Dominó traducción, voz y series temporales hasta la llegada del Transformer.', impl:'torch.nn.LSTM' },
  { id:'lenet-1998', t:'Gradient-based learning applied to document recognition', a:'Y. LeCun, L. Bottou, Y. Bengio, P. Haffner', y:1998, v:'Proceedings of the IEEE 86(11), 2278–2324', area:'CNN',
    p:'Reconocer caracteres manuscritos sin diseñar las características a mano.',
    c:'Redes convolucionales entrenadas de extremo a extremo (LeNet-5) y el dataset MNIST.',
    arch:'Convoluciones, submuestreo y capas totalmente conectadas.', r:'Estableció la receta de las CNN que luego escaló a ImageNet.', impl:'torch.nn.Conv2d' },
  { id:'rf-2001', arts:['random-forest'], t:'Random Forests', a:'L. Breiman', y:2001, v:'Machine Learning 45(1), 5–32', area:'Ensembles',
    p:'Los árboles de decisión individuales son inestables y sobreajustan.',
    c:'Combinar árboles decorrelacionados mediante bootstrap y selección aleatoria de variables en cada nodo; error out-of-bag.',
    arch:'Conjunto de árboles CART no podados que votan.', r:'Uno de los algoritmos más usados en datos tabulares por su robustez.', impl:'sklearn.ensemble.RandomForestClassifier', lab:'tree' },
  { id:'alexnet-2012', t:'ImageNet Classification with Deep Convolutional Neural Networks', a:'A. Krizhevsky, I. Sutskever, G. E. Hinton', y:2012, v:'NeurIPS 2012', area:'Visión artificial',
    p:'Clasificar 1,2 millones de imágenes de ImageNet en 1.000 categorías.',
    c:'Una CNN profunda entrenada en GPU con ReLU y dropout que redujo drásticamente el error en ILSVRC-2012.',
    arch:'AlexNet: 5 capas convolucionales y 3 totalmente conectadas.', r:'Marcó el inicio de la era moderna del deep learning.', impl:'torchvision.models.alexnet' },
  { id:'dropout-2014', t:'Dropout: A Simple Way to Prevent Neural Networks from Overfitting', a:'N. Srivastava, G. Hinton, A. Krizhevsky, I. Sutskever, R. Salakhutdinov', y:2014, v:'JMLR 15, 1929–1958', area:'Regularización',
    p:'Las redes grandes sobreajustan con facilidad.',
    c:'Apagar neuronas al azar durante el entrenamiento, lo que equivale a promediar muchas subredes.',
    arch:'Aplicable a cualquier capa.', r:'Técnica de regularización estándar en redes profundas.', impl:'torch.nn.Dropout', lab:'overfit' },
  { id:'adam-2015', arts:['neural-networks'], t:'Adam: A Method for Stochastic Optimization', a:'D. P. Kingma, J. Ba', y:2015, v:'ICLR 2015', area:'Optimización',
    p:'Elegir una tasa de aprendizaje que funcione para todos los parámetros.',
    c:'Pasos adaptativos por parámetro con estimaciones de primer y segundo momento del gradiente y corrección de sesgo.',
    arch:'Optimizador.', r:'El optimizador por defecto en la mayoría de redes profundas.', impl:'torch.optim.Adam', lab:'gd' },
  { id:'dqn-2015', t:'Human-level control through deep reinforcement learning', a:'V. Mnih et al.', y:2015, v:'Nature 518, 529–533', area:'Aprendizaje por refuerzo',
    p:'Aprender a jugar a partir de los píxeles de la pantalla y la puntuación.',
    c:'Deep Q-Network: Q-learning con una CNN, experience replay y red objetivo; nivel humano en muchos juegos de Atari 2600.',
    arch:'CNN que estima el valor Q de cada acción.', r:'Punto de partida del deep reinforcement learning.', impl:'Stable-Baselines3 DQN' },
  { id:'resnet-2016', t:'Deep Residual Learning for Image Recognition', a:'K. He, X. Zhang, S. Ren, J. Sun', y:2016, v:'CVPR 2016', area:'Visión artificial',
    p:'Las redes muy profundas eran más difíciles de optimizar que las menos profundas.',
    c:'Conexiones residuales: cada bloque aprende una corrección que se suma a su entrada.',
    arch:'ResNet, con variantes de hasta 152 capas en ImageNet.', r:'Las conexiones residuales están en casi toda arquitectura moderna, incluido el Transformer.', impl:'torchvision.models.resnet50' },
  { id:'xgboost-2016', arts:['gradient-boosting'], t:'XGBoost: A Scalable Tree Boosting System', a:'T. Chen, C. Guestrin', y:2016, v:'KDD 2016', area:'Ensembles',
    p:'Hacer gradient boosting de árboles rápido y escalable.',
    c:'Objetivo regularizado, algoritmo consciente de la dispersión de los datos y optimizaciones de sistema.',
    arch:'Árboles de boosting.', r:'Referente en competiciones y en la industria con datos tabulares.', impl:'xgboost.XGBClassifier' },
  { id:'attention-2017', arts:['transformers'], t:'Attention Is All You Need', a:'A. Vaswani, N. Shazeer, N. Parmar, J. Uszkoreit, L. Jones, A. N. Gomez, Ł. Kaiser, I. Polosukhin', y:2017, v:'NeurIPS 2017', area:'Transformers',
    p:'Las RNN procesan en secuencia, lo que limita el paralelismo y las dependencias largas.',
    c:'El Transformer: solo atención multi-cabeza y capas feed-forward, con codificación posicional.',
    arch:'Encoder–decoder de 6 + 6 capas, d_model = 512, 8 cabezas en el modelo base.', r:'La arquitectura de BERT, GPT y prácticamente todos los LLM.', impl:'torch.nn.Transformer', lab:'attn' },
  { id:'gpt-2018', arts:['transformers'], t:'Improving Language Understanding by Generative Pre-Training', a:'A. Radford, K. Narasimhan, T. Salimans, I. Sutskever', y:2018, v:'Informe técnico de OpenAI', area:'GPT',
    p:'Aprovechar texto sin etiquetar para mejorar tareas de lenguaje con pocos datos.',
    c:'Preentrenamiento generativo con un decoder Transformer seguido de fine-tuning supervisado.',
    arch:'Decoder Transformer de 12 capas.', r:'Origen de la familia GPT.', impl:'transformers.OpenAIGPTModel' },
  { id:'bert-2019', arts:['transformers'], t:'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding', a:'J. Devlin, M.-W. Chang, K. Lee, K. Toutanova', y:2019, v:'NAACL 2019', area:'BERT',
    p:'Los modelos de lenguaje preentrenados solo miraban el contexto en una dirección.',
    c:'Encoder bidireccional preentrenado con modelado de lenguaje enmascarado y predicción de la siguiente frase.',
    arch:'Encoder Transformer (base: 12 capas; large: 24).', r:'Revolucionó la comprensión del lenguaje y los buscadores.', impl:'transformers.BertModel' },
  { id:'gpt3-2020', arts:['transformers'], t:'Language Models are Few-Shot Learners', a:'T. B. Brown et al.', y:2020, v:'NeurIPS 2020', area:'GPT',
    p:'Cada tarea necesitaba su propio fine-tuning con datos etiquetados.',
    c:'GPT-3, de 175.000 millones de parámetros, resuelve tareas nuevas con unos pocos ejemplos en el prompt (in-context learning).',
    arch:'Decoder Transformer de 96 capas.', r:'Demostró el efecto de la escala e inauguró la era de los LLM.', impl:'—' },
  { id:'rag-2020', t:'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', a:'P. Lewis et al.', y:2020, v:'NeurIPS 2020', area:'RAG',
    p:'El conocimiento guardado en los parámetros es difícil de actualizar y de citar.',
    c:'Combinar un recuperador denso de documentos con un generador seq2seq entrenados conjuntamente.',
    arch:'Recuperador DPR + generador BART.', r:'Dio nombre y forma a los sistemas RAG actuales.', impl:'LangChain, LlamaIndex, pgvector' },
  { id:'clip-2021', t:'Learning Transferable Visual Models From Natural Language Supervision', a:'A. Radford et al.', y:2021, v:'ICML 2021', area:'Multimodal',
    p:'Los modelos de visión necesitaban etiquetas fijas y costosas.',
    c:'CLIP: entrenar imagen y texto en un espacio común con aprendizaje contrastivo sobre pares imagen–texto de internet.',
    arch:'Encoder de imagen (ResNet o ViT) + encoder de texto Transformer.', r:'Base de muchos modelos multimodales y generadores de imágenes.', impl:'open_clip' },
  { id:'lora-2022', t:'LoRA: Low-Rank Adaptation of Large Language Models', a:'E. J. Hu et al.', y:2022, v:'ICLR 2022', area:'Fine-tuning',
    p:'Ajustar todos los parámetros de un modelo enorme es carísimo.',
    c:'Congelar los pesos y aprender actualizaciones de bajo rango ΔW = B·A en las capas de atención.',
    arch:'Adaptadores de bajo rango.', r:'La forma estándar de hacer fine-tuning de LLM con poco hardware.', impl:'peft.LoraConfig' },
];

/* Datasets reales y conocidos. */
const DATASETS = [
  { id:'iris', t:'Iris', src:'R. A. Fisher (1936) · UCI · sklearn.datasets.load_iris', n:'150 filas', vars:'4 numéricas (largo y ancho de sépalo y pétalo, en cm)', types:'float', task:'Clasificación en 3 especies', models:'Regresión logística, KNN, árbol de decisión', ex:'5.1, 3.5, 1.4, 0.2 → setosa' },
  { id:'breast', t:'Breast Cancer Wisconsin (Diagnostic)', src:'UCI · sklearn.datasets.load_breast_cancer', n:'569 filas (212 malignos, 357 benignos)', vars:'30 numéricas calculadas sobre imágenes de núcleos celulares', types:'float', task:'Clasificación binaria', models:'Random Forest, regresión logística, SVM', ex:'mean radius, worst area, worst concave points…', arts:['random-forest', 'logistic-regression'] },
  { id:'diabetes', t:'Diabetes', src:'Efron, Hastie, Johnstone y Tibshirani (2004) · sklearn.datasets.load_diabetes', n:'442 pacientes', vars:'10 numéricas (edad, sexo, índice de masa corporal, tensión media y seis análisis de sangre), ya centradas y escaladas', types:'float', task:'Regresión de la progresión de la enfermedad al año (25–346)', models:'Regresión lineal, Ridge, gradient boosting', arts:['linear-regression', 'gradient-boosting'] },
  { id:'california', t:'California Housing', src:'Censo de EE. UU. de 1990 · sklearn.datasets.fetch_california_housing', n:'20.640 filas', vars:'8 numéricas (ingresos medios, edad de la vivienda, habitaciones, latitud, longitud…)', types:'float', task:'Regresión del valor mediano de la vivienda', models:'Gradient boosting, Random Forest, regresión lineal' },
  { id:'ai4i', t:'AI4I 2020 Predictive Maintenance', src:'UCI Machine Learning Repository', n:'10.000 filas', vars:'Tipo de producto, temperatura del aire y del proceso, velocidad de giro, par, desgaste de herramienta y 5 modos de fallo', types:'categórica, float, int, binaria', task:'Clasificación de fallos de máquina (muy desbalanceada)', models:'Gradient boosting, Random Forest con class_weight', proj:'mantenimiento' },
  { id:'digits', t:'Digits', src:'UCI Optical Recognition of Handwritten Digits · sklearn.datasets.load_digits', n:'1.797 imágenes (unas 180 por dígito)', vars:'64 píxeles (imágenes de 8×8) con valores de 0 a 16', types:'int', task:'Clasificación de dígitos 0–9', models:'Regresión logística, MLP, SVM', arts:['neural-networks'] },
  { id:'mnist', t:'MNIST', src:'LeCun et al. (1998)', n:'70.000 imágenes (60.000 de entrenamiento y 10.000 de test)', vars:'Imágenes de 28×28 píxeles en escala de grises', types:'uint8', task:'Clasificación de dígitos 0–9', models:'MLP, CNN' },
  { id:'cifar10', t:'CIFAR-10', src:'A. Krizhevsky (2009)', n:'60.000 imágenes (50.000 / 10.000)', vars:'Imágenes en color de 32×32 píxeles', types:'uint8 RGB', task:'Clasificación en 10 clases de objetos', models:'CNN, ResNet, Vision Transformer' },
  { id:'wine', t:'Wine Quality', src:'Cortez et al. (2009) · UCI', n:'6.497 filas (1.599 tintos, 4.898 blancos)', vars:'11 fisicoquímicas (acidez, azúcar residual, sulfatos, alcohol…)', types:'float', task:'Regresión o clasificación de la calidad (0–10)', models:'Random Forest, gradient boosting' },
  { id:'imdb', t:'IMDB Large Movie Review', src:'Maas et al. (2011)', n:'50.000 reseñas (25.000 / 25.000)', vars:'Texto libre en inglés', types:'texto', task:'Análisis de sentimiento binario', models:'Naive Bayes con TF-IDF, LSTM, BERT' },
];

/* Ruta de aprendizaje en 10 niveles. */
const PATH = [
  { n:1, t:'Matemáticas', th:'Vectores y matrices, derivadas y regla de la cadena, gradientes, probabilidad básica.', ex:'Calcula a mano el gradiente de f(x, y) = x² + 3xy y comprueba el resultado con diferencias finitas en Python.', pr:'Implementa el descenso de gradiente para minimizar una función de dos variables y dibuja la trayectoria.', ok:'Sabes explicar qué es un gradiente y por qué se resta en cada paso.', labs:['gd','sigmoid'], lesson:'lesson-1' },
  { n:2, t:'Python', th:'Sintaxis, funciones, NumPy vectorizado, Pandas y Matplotlib.', ex:'Carga un CSV con Pandas, limpia valores nulos y agrupa por una columna.', pr:'Análisis exploratorio completo del dataset Wine Quality con gráficos.', ok:'Escribes código NumPy sin bucles innecesarios y usas groupby con soltura.', labs:[] },
  { n:3, t:'Estadística', th:'Distribuciones, media y varianza, correlación, teorema central del límite, contraste de hipótesis, Bayes.', ex:'Simula el teorema central del límite con medias de muestras de una distribución exponencial.', pr:'Estudio de correlaciones y outliers en California Housing.', ok:'Distingues correlación de causalidad y sabes interpretar un intervalo de confianza.', labs:[] },
  { n:4, t:'Machine Learning', th:'Supervisado y no supervisado, validación, sobreajuste, regularización, árboles y ensembles, métricas.', ex:'Compara un árbol y un Random Forest con validación cruzada de 5 particiones.', pr:'Clasificador de fallos con AI4I 2020, con métricas adecuadas para clases desbalanceadas.', ok:'Eliges la métrica correcta y detectas sobreajuste con curvas de validación.', labs:['overfit','reg','tree','kmeans'] },
  { n:5, t:'Deep Learning', th:'Neuronas, activaciones, MLP, backpropagation, optimizadores, CNN y RNN.', ex:'Implementa en NumPy una red de una capa oculta y verifica su gradiente numéricamente.', pr:'CNN en PyTorch para CIFAR-10 con aumento de datos.', ok:'Puedes escribir un bucle de entrenamiento en PyTorch desde cero y depurarlo.', labs:['boundary','backprop'] },
  { n:6, t:'Transformers', th:'Tokenización, embeddings, codificación posicional, self-attention, multi-head, bloques residuales.', ex:'Implementa scaled dot-product attention en PyTorch y compara con nn.MultiheadAttention.', pr:'Un mini-GPT a nivel de carácter entrenado con un texto en castellano.', ok:'Sabes decir la forma de cada tensor en un bloque Transformer.', labs:['attn'], route:'transformer' },
  { n:7, t:'LLM', th:'Preentrenamiento, fine-tuning, LoRA, muestreo, cuantización, RAG, evaluación.', ex:'Haz fine-tuning con LoRA de un modelo pequeño de Hugging Face.', pr:'Sistema RAG sobre tus propios documentos con pgvector.', ok:'Explicas cuándo conviene RAG y cuándo fine-tuning.', labs:[] },
  { n:8, t:'MLOps', th:'Docker, APIs con FastAPI, bases de datos, CI/CD, monitorización y deriva de datos.', ex:'Empaqueta un modelo de scikit-learn en una API FastAPI dentro de Docker.', pr:'Despliegue del modelo de mantenimiento predictivo con monitorización.', ok:'Tu modelo se levanta con docker compose up y tiene tests.', labs:[] },
  { n:9, t:'Agentes IA', th:'Uso de herramientas, planificación, memoria, evaluación y seguridad de agentes.', ex:'Un agente que responde preguntas consultando una API y una base de datos.', pr:'Agente de soporte técnico con RAG y herramientas, con registro de trazas.', ok:'Mides la tasa de éxito del agente con un conjunto de casos de prueba.', labs:[] },
  { n:10, t:'Investigación', th:'Leer papers, reproducir resultados, diseñar experimentos y ablaciones.', ex:'Reproduce una figura de un paper clásico.', pr:'Replica un paper de la biblioteca con código abierto y documenta las diferencias.', ok:'Puedes defender una hipótesis con experimentos controlados.', labs:[], route:'papers' },
];

/* Proyectos. Solo el primero está desarrollado; el resto se marcan como planificados. */
const PROJECTS = [
  { id:'mantenimiento', t:'Mantenimiento predictivo en fresadoras', area:'Industria 4.0', status:'Plan detallado', d:'Predecir fallos de máquina con el dataset AI4I 2020 para programar mantenimiento antes de la avería.' },
  { id:'telecom', t:'Predicción de bajas de clientes', area:'Telecomunicaciones', status:'Planificado', d:'Clasificación de churn con datos de uso y facturación.' },
  { id:'redes', t:'Detección de anomalías en tráfico de red', area:'Redes', status:'Planificado', d:'Modelos no supervisados sobre flujos de red para detectar comportamientos anómalos.' },
  { id:'energia', t:'Previsión de demanda eléctrica', area:'Energía', status:'Planificado', d:'Series temporales con estacionalidad diaria y semanal.' },
  { id:'vision', t:'Inspección visual de defectos', area:'Visión artificial', status:'Planificado', d:'Clasificación de imágenes de piezas con CNN y transfer learning.' },
  { id:'rag', t:'Asistente RAG documental', area:'RAG · Agentes', status:'Planificado', d:'Preguntas y respuestas sobre documentación técnica propia con pgvector.' },
];
